
resources:
- ../../base
- svc.yaml

namespace: dev-dataapp 

images:
- name: rameezdocker69/dataapp
  newName: rameezdocker69/dataapp
  newTag: d94d7d755359577b1811b2cdba6bb6c90b9f3c8b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
