apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-app
  labels:
    app: data-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: data-app
  template:
    metadata:
      labels:
        app: data-app
    spec:
      containers:
        - name: data-app
          image: rameezdocker69/dataapp:latest   # 🔹 base uses 'latest'
          ports:
            - containerPort: 80


