
apiVersion: v1
kind: Service
metadata:
  name: data-app-service
spec:
  selector:
    app: data-app
  ports:
    - protocol: TCP
      port: 80        # external port for clients
      targetPort: 8080 # forwards traffic to the container's port
  type: NodePort


